import typing as t

from aws_cdk import NestedStack
from aws_cdk import aws_s3_deployment as aws_s3d
from constructs import Construct

from cdk_stack.bucket_stack import BucketStack

# mobile app assets ('eagle' intro, sounds etc) as well as data.json generated by jobs (lambdas)


class AssetsStack(NestedStack):
    def __init__(
        self, scope: Construct, construct_id: str, bucket_stack: BucketStack, **kwargs: dict[str, t.Any]
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        aws_s3d.BucketDeployment(
            self,
            id="bucket-deployment-assets",
            destination_bucket=bucket_stack.bucket,
            destination_key_prefix="assets",
            sources=[
                aws_s3d.Source.asset("../mobile-app/assets"),
            ],
        )
